spring.application.name=SpringBootJPA

spring.datasource.url=jdbc:h2:mem:testdb;NON_KEYWORDS=USER
spring.h2.console.enabled=true
spring.data.jpa.repositories.bootstrap-mode=default
spring.jpa.defer-datasource-initialization=true


currency-service.url=http://vengat.com
currency-service.username=vengat
